[workspace]
authors = ["Eliska Pospechova <ela.pospechova@gmail.com>"]
channels = ["conda-forge"]
name = "evolution"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.5,<5"
geopandas = ">=1.1.1,<2"
pyarrow = ">=21.0.0,<22"
pysal = ">=25.7,<26"
numba = ">=0.61.2,<0.62"
lonboard = ">=0.11.1,<0.12"
httpx = ">=0.28.1,<0.29"
py7zr = ">=1.0.0,<2"
gdal = { version = ">=3.10.3,<4", channel = "conda-forge" }
